version: '3.7'
services:


  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db4
      - ./db-init/:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cs493final
      MONGO_INITDB_DATABASE: final
      MONGO_USER: cs493final
      MONGO_PASSWORD: cs493final
      
  mysql:
    image: mysql:5
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: cs493final
      MYSQL_USER: cs493final
      MYSQL_PASSWORD: cs493final


volumes:
  mongo-data:
  mysql-data:
    name: project-mysql-data

