version: '3.7'
services:
  api:
    build: .
    image: tarpaulin-api
    restart: always
    ports:
      - 8000:8000
    environment:
      MYSQL_DATABASE: tarpaulin-api
      MYSQL_USER: tarpaulin-user
      MYSQL_PASSWORD: hunter2
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306

  mysql:
    image: mysql:5
    restart: always
    volumes:
      - tarpaulin-api:/var/lib/mysql/
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tarpaulin-api
      MYSQL_USER: tarpaulin-user
      MYSQL_PASSWORD: hunter2
    ports:
     - "3306:3306"

volumes:
  tarpaulin-api:
